stages:
  - mirror from github

mirror_from_github:
  stage: mirror from github
  tags:
    - docker
  only:
    - schedules
  before_script:
    - apt update -qq && apt install -y -qq git
    - git config --global user.name "${GITLAB_USER_NAME}"
    - git config --global user.email "${GITLAB_USER_EMAIL}"
  script:
# MASTER
    - git checkout master
    - git reset --hard origin/master
    - rm -fr ".git/rebase-merge"
    - git pull --ff-only "https://github.com/qgis/QGIS.git" master
    - git push -f "https://gitlab-ci-token:${GIT_TOKEN}@git.oslandia.net/Oslandia/Oslandia-3d/qgis.git" master
# DEVELOP
    - git checkout develop
    - git pull --rebase origin master
    - git push -f "https://gitlab-ci-token:${GIT_TOKEN}@git.oslandia.net/Oslandia/Oslandia-3d/qgis.git" develop
