stages:
  - mirror from github

mirror_from_github:
  stage: mirror from github
  only:
    - schedules
  before_script:
    - apt update -qq && apt install -y -qq git openssh-client
    - eval $(ssh-agent -s)
    - echo "${GIT_SSH_PRIVATE_KEY}" | tr -d '\r' | ssh-add -
    - mkdir -p ~/.ssh
    - chmod 700 ~/.ssh
    - ssh-keyscan $GIT_LAB_HOST >> ~/.ssh/known_hosts
    - chmod 644 ~/.ssh/known_hosts
    - git config --global user.name "${GITLAB_USER_NAME}"
    - git config --global user.email "${GITLAB_USER_EMAIL}"
  script:
    - git checkout master
    - git pull
    - git pull --ff-only "https://github.com/qgis/QGIS.git" master
    - git push -f "git@gitlab.com:Oslandia/qgis/qgis.git" master
