stages:
  - mirror from github

mirror_from_github:
  stage: mirror from github
  tags:
    - docker
  only:
    - schedules
  before_script:
    - apt update -qq && apt install -y -qq git
    - git config --global user.name "${GITLAB_USER_NAME}"
    - git config --global user.email "${GITLAB_USER_EMAIL}"
  script:
# MASTER
    - git checkout master
    - rm -fr ".git/rebase-merge"
    - git remote | grep -q upstream || git remote add upstream "https://github.com/qgis/QGIS.git"
    - git fetch upstream
    - git branch | grep -q github_master && git checkout github_master || git checkout -b github_master upstream/master
    - git push -f "https://gitlab-ci-token:${GIT_TOKEN}@git.oslandia.net/Oslandia/Oslandia-3d/qgis.git" HEAD:master
# DEVELOP
    - git checkout develop
    - git rebase origin/master
    - git push -f "https://gitlab-ci-token:${GIT_TOKEN}@git.oslandia.net/Oslandia/Oslandia-3d/qgis.git" develop
