stages:
  - mirror from github

mirror_from_github:
  stage: mirror from github
  tags:
    - docker
  only:
    - schedules
  before_script:
    - apt update -qq && apt install -y -qq git
    - git config --global user.name "${GITLAB_USER_NAME}"
    - git config --global user.email "${GITLAB_USER_EMAIL}"
# create dedicated directory to clone as we may have gitlab cache (via docker volumes)
    - rm -rf /tmp/qgis
    - mkdir -p /tmp/
    - cd /tmp/
    - git clone "https://gitlab-ci-token:${GIT_TOKEN}@git.oslandia.net/Oslandia/Oslandia-3d/qgis.git"
    - cd qgis
  script:
# MASTER
    - git branch
    - git remote -v
    - git remote add upstream "https://github.com/qgis/QGIS.git"
    - git fetch upstream master
    - git checkout -b github_master upstream/master
    - git push -f "https://gitlab-ci-token:${GIT_TOKEN}@git.oslandia.net/Oslandia/Oslandia-3d/qgis.git" HEAD:master
# DEVELOP
    - git fetch origin
    - git checkout -b develop origin/develop
    - git rebase origin/master
    - git push -f "https://gitlab-ci-token:${GIT_TOKEN}@git.oslandia.net/Oslandia/Oslandia-3d/qgis.git" develop
# remove dedicated directory
after_script:
    - rm -rf /tmp/qgis
